### ISSUE TITLE
getScreenCTM / pageX conflict

### ISSUE THREAD

**Issue by CGamesPlay** [svgdotjs/svg.draggable.js#100]
`DragHandler.transformPoint` takes `touches.pageY` and then applies `this.m`, which is equal to `this.el.node.getScreenCTM().inverse()`. `pageY` will vary based on the scroll position in the document, and `getScreenCTM()` will as well. The net result is that the points that come out of `transformPoint` have the scroll offset applied twice.

A fix that works in my vendored copy is to the `clientY` instead, since this does not vary with scroll position.

**Comment by Fuzzyma** [comment]
That is totally correct and should be that way. Can you open a PR to change it?
