### ISSUE TITLE
Problem with import statement

### ISSUE THREAD

**Issue by andersoxie** [svgdotjs/svg.draggable.js#104]
When I use the svg.draggable.js in my system  I get an error at the first row:

import { Box, Element, G, extend, off, on } from '@svgdotjs/svg.js'

"Uncaught SyntaxError: Unexpected token {"

Any idea of why I get that? I can not see any problems with the import statement

**Comment by Fuzzyma** [comment]
Can you please elaborate further? Which version do you use? What is your exact code? Could it be, that it has something to do with #103?

**Comment by andersoxie** [comment]
I worked around #103 but did not get it to work. I think I have problems with how to use npm etc. I instead tried with svg.draggy.js and that library did not use import and then it worked well.

**Comment by Fuzzyma** [comment]
svg.draggable.js also works without imports. Just put a good old script tag into your html and load the lib
