### ISSUE TITLE
this.el.dispatch is not a function

### ISSUE THREAD

**Issue by jonathan-roy** [svgdotjs/svg.draggable.js#105]
Hi,

I am new to SVG.js so I think I am missing something, but I try to make an image draggable using this plugin and I have the following error when I try to drag the image:
```
Uncaught TypeError: this.el.dispatch is not a function
    at DragHandler.startDrag (/Users/jroy/Workspace/test/node_modules/svg.draggable.js/dist/svg.draggable.js:84:21)
```

I am using it within a Vue.js component, here is the code:
```html
<template>
	<div>
		<div id="svgjs-container" style="width:100%; height:400px; background-color:#888888;" />
	</div>
</template>

<script>

import SVG from "svg.js";
import "svg.draggable.js";

export default {
	data() {
		return {
			"draw": null
		};
	},
	mounted() {
		this.draw = SVG("svgjs-container");
		this.draw
			.image("blogdown.svg")
			.draggable();
	}
};

</script>
```

**Comment by Fuzzyma** [comment]
Which version are you using? If it is svg.draggabe.js v3 please use 2.x instead.
Explanation is here: #103

**Comment by andywu1314** [comment]
Still have this problem

**Comment by vsvanshi** [comment]
Hi Fuzzyma, I am also facing the same problem.
The version downloaded from @svgdotjs/svg.draggable.js is 3.0.2
Not able to find the 2.x version anywhere

**Comment by Fuzzyma** [comment]
The old version was installed using `npm i svg.draggable.js`.
All svg.js v3 compatible stuff is in the @svgdotjs org. Everything else is not!

**Comment by vsvanshi** [comment]
Hi Fuzzyma,
thanks for getting back on this so soon.
Yes, version 2.x fixes that problem.

Anyone else looking for the solution, make sure you intall using :`npm i svg.draggable.js@2.x`
