### ISSUE TITLE
handler.move is not a function

### ISSUE THREAD

**Issue by notchris** [svgdotjs/svg.draggable.js#106]
I followed the example for grid snapping, but I get this error when attempting a drag.
> Uncaught TypeError: handler.move is not a function at initializer.rect.on

```
let draw = SVG('stage').size(window.innerWidth, window.innerHeight)
        let rect = draw.rect(100, 100).attr({ fill: '#f06' }).selectize().resize().draggable()
        rect.on('dragmove.namespace', (e) => {
          const {handler, box} = e.detail
          e.preventDefault()

          handler.move(box.x - box.x % 50, box.y - box.y % 50)
        })
```

I'm using an older version (2.0.0) per the compatibility issue with 3.0.

Thanks for your help!

**Comment by Fuzzyma** [comment]
If you use an older version, use the old readme, too. Ofc things changed and what you try to do is possible with 3.x but not with 2.x. Just select the 2.x branch and you will see the old readme
