### ISSUE TITLE
Uncaught TypeError: Cannot read property 'put' of null

### ISSUE THREAD

**Issue by weiQing88** [svgdotjs/svg.draggable.js#107]
**based on the example, Then an exception is reported ：**
 Uncaught TypeError: Cannot read property 'put' of null。

> "@svgdotjs/svg.draggable.js": "^3.0.0",
>     "@svgdotjs/svg.js": "^3.0.12",

code : 
`var draw = SVG().addTo('myDrawing').size(400, 400) 
var rect = draw.rect(100, 100)
     rect.draggable()`

**Comment by Fuzzyma** [comment]
Can you create a jsfiddle?

**Comment by weiQing88** [comment]
> Can you create a jsfiddle?
 wait a momen

**Comment by weiQing88** [comment]
> Can you create a jsfiddle?

https://jsfiddle.net/wx1988/cmyoLk7u/3/#

**Comment by Fuzzyma** [comment]
`addTo` expectes a query seletor. `myDrawing` has to be `#myDrawing`

https://jsfiddle.net/Fuzzy/asxg48ok/1/

**Comment by weiQing88** [comment]
> `addTo` expectes a query seletor. `myDrawing` has to be `#myDrawing`
> 
> https://jsfiddle.net/Fuzzy/asxg48ok/1/
> 
> // EDIT: Corrected Readme

thanks friend
