### ISSUE TITLE
How can we import svg.draggable.js without node js imoprt

### ISSUE THREAD

**Issue by nkpdn** [svgdotjs/svg.draggable.js#108]

**Comment by nkpdn** [comment]
In jsp page I wanted to import svg.draggable.js but not able to import as earlier ( 2.2.2 v ), cant we import without node?

**Comment by Fuzzyma** [comment]
Sorry I don't understand your question. What do you want to do? Do you have code to show us?

**Comment by nkpdn** [comment]
I have downloaded svg.draggable.js from git and stored it in some directory and included in jsp as <script src="--some location--/svg.draggable.js" ></script> after <script type="application/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.6.6/svg.min.js"></script>, but it throwing error as uncaught syntax : unexpected token { -> for import, but if download svg.draggable.js from 2.2.2 tag it will work.

refere this error
![Screenshot (17)](https://user-images.githubusercontent.com/44496883/55397006-df1ebb80-5562-11e9-9d21-a44663641054.png)

**Comment by Fuzzyma** [comment]
Its seems like you are mixing esm modules with normal script tags. If you use `import` you dont need to include the draggable script. Beside that, 2.6 doesnt work with esm. You need 3.x (newest is 3.0.12).

Beside the esm-thing you ofc need the right version for the right version. The new draggable only works with svg.js v3 while older versions work with v2.

Please sort out what you actually want to use.

**Comment by Fuzzyma** [comment]
Closing this for now. As soon as new pieces of information available we can reopen
