### ISSUE TITLE
Draggable missing from Angular 7 production build

### ISSUE THREAD

**Issue by maxailloud** [svgdotjs/svg.draggable.js#109]
I am using svg.js alongside svg.draggable.js in a Angular 7 application built using Angular-cli.
Locally everything is working fine but once i do a production build I get the error `.draggable is not a function`.

Here's how I use both of them in my component:
```typescript
import * as SvgJs from '@svgdotjs/svg.js';
import '@svgdotjs/svg.draggable.js';
```

It's like if bor the production build Angular-cli is not including svg.draggable.

Maybe I need to do something more but as it's working locally I don't really know what.
Does anyone knows why it happens and how to solve this?

Maybe it's not related to svg.draggable.js specifically but to Angular-cli by the way but got the issue with this.

**Comment by Fuzzyma** [comment]
Its pretty unlikely that someone will stumble over this question here. Unfortunately I cannot help you with this issue because I am neither familar with angular nor with typescript.

You might want to ask this on stackoverflow so you question is seen!

**Comment by maxailloud** [comment]
My issue came from the fact that I was using a branch of my fork, so not the compiled version of it. I published my fork over to a private npm and it worked. Now with the new tag it works even with the official package.

So my bad on this one.
