### ISSUE TITLE
Detect a click-Event

### ISSUE THREAD

**Issue by zippy84** [svgdotjs/svg.draggable.js#111]
Is there a better way to detect a simple click?

```JavaScript
gr.on('dragstart.namespace', (e) => {
    let ev = e.detail.event;
    $(gr.node).data('xy', [ev.clientX, ev.clientY]);
});

gr.on('dragend.namespace', (e) => {
    let ev = e.detail.event,
        old = $(gr.node).data('xy');

    if (old[0] != ev.clientX || old[1] != ev.clientY) {
        // dragged
    } else {
        // clicked
    }
});
```

**Comment by Fuzzyma** [comment]
what about `on('click', function() {})`

**Comment by zippy84** [comment]
Because dragend is fired before click. There is no movement, but alle drag*-handler will be called.

**Comment by Fuzzyma** [comment]
In that case your solution is the correct one i guess

**Comment by Fuzzyma** [comment]
I will try to integrate a check for this so no draghandlers are called when no movement happend. However, beforedrag and dragstart might be called anyway because they are called before any information about movement is available

**Comment by Fuzzyma** [comment]
The easiest way with current master is to bind to dragmove and dragend. In dragmove you set a variable `isDrag = true` and in dragEnd you execute logic if `isDraw == false`
