### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by jsh562** [svgdotjs/svg.draggable.js#113]
very similar to https://github.com/svgdotjs/svg.draggable.js/issues/104

It errors on the Import statement.

I downloaded the .zip, extracted, included the only svg.draggable.js file, which is in /src/ folder - there is no /dist/ folder, with script tag
<script src="/src/svg.draggable.js"></script>

**Comment by abdulbasit010** [comment]
please use the bundled file when you want to use svg.js and draggable.js that way. You can download them on the release page on github, load them via npm or use a cdn like this one: 

https://unpkg.com/@svgdotjs/svg.js@3.0.16/dist/svg.min.js
https://unpkg.com/@svgdotjs/svg.draggable.js@3.0.2/dist/svg.draggable.min.js

**Comment by grayter1** [comment]
Where can I found no minified code? I would like to create my own extension but all your extensions for v.3 are minified. I cannot use ES6 in my project.

**Comment by Fuzzyma** [comment]
Download via npm and import it. As you can see we do that in our extensions, too. Just take a look into the src folder of this repo

**Comment by grayter1** [comment]
Yes but I need no es6 version

**Comment by Fuzzyma** [comment]
In that take a look at releases were you find a bundled version.
