### ISSUE TITLE
Constraints - Deleting SVGs - Moving & Selecting in Groups

### ISSUE THREAD

**Issue by alextate4** [svgdotjs/svg.draggable.js#118]
My team is working on a floor planning application using SVGs. We would like to know if the following features are possible in svg.draggable.js:

1. Setting constraints so that SVGs cannot run into one another.

2. Grouping, moving, and rotating objects together through an event like a mouse drag and removing single items in that group with a shift+click.

3. Deletion of SVGs or entire group of SVGs at the same time.

The project is hosted on http://colab.web.csit.jccc.edu/

Github:
https://github.com/Colab-JCCC-Team/colab.git

We appreciate all of your work and hope to hear back from you soon.

**Comment by Fuzzyma** [comment]
1. You can add that custom behavior to the dragmove event
2. draggable only moves objects but you can certainly group objects and move them together. For rotation you are better off with svg.resize.js. Deleting items with shift click is again custom behavior you can program on your own
3. `remove()`?

**Comment by alextate4** [comment]
Thank you! My apologies I am still new to coding. I found an algorithm that will work for movement constraints.

**Comment by Fuzzyma** [comment]
No need to apologize. What you are building looks great. Have a chat anytime over at gitter if you got more questions.
