### ISSUE TITLE
can't "install" it

### ISSUE THREAD

**Issue by VitaliyAT** [svgdotjs/svg.draggable.js#121]
1.) HTML
```
<script src="svg.js"></script>
<script src="svg.draggable.js"></script>
```
svg.js is 3.0.16
2) JS
```
var draw = SVG().putIn('#svg_js');
rect = draw.rect(20, 45).fill('#f00').draggable();
```
3) FireFox console
> SyntaxError: import declarations may only appear at top level of a module svg.draggable.js:1
> TypeError: draw.rect(...).fill(...).draggable is not a function

What I do not right?

**Comment by Fuzzyma** [comment]
You are using the file from the src folder which is the esm version. You need to include the bundled version which is available over npm (in the dist folder) or here on github under relases zipped
