### ISSUE TITLE
Sentry error

### ISSUE THREAD

**Issue by jonalxh** [svgdotjs/svg.draggable.js#123]
Hi, I'm not sure if posting it here, I'm actually using Sentry in my Vue project and it is showing me the following error suggesting me to do a bug report.

`
/*! svg.draggable.js - v2.2.2 - 2019-01-08
https://github.com/svgdotjs/svg.draggable.js
Copyright (c) 2019 Wout Fierens; Licensed MIT 
*/

{snip} please open a bug report.")}function ze(e){var t;try{throw new Error("Sentry syntheticException")}catch(e){t=e}return Le("captureException", {snip}
`

I hope it be the correct place.

**Comment by Fuzzyma** [comment]
Nope unfortunately not. Or is Sentry some kind of black magic which knows were an error happend? :D

I guess thats more of a Sentry Error (see: `throw new Error("Sentry syntheticException"`)

**Comment by jonalxh** [comment]
I've posted it on Sentry, thanks for your help.
