### ISSUE TITLE
How to get rbox in dragmove?

### ISSUE THREAD

**Issue by moayuisuda** [svgdotjs/svg.draggable.js#126]
I am following the example code to move the rectangle in a constraint, but when the rectangle has transform, the position is not correct.
```js
const rect = draw.rect();
const constraints = new Box(0, 0, 1600, 768);

rect.transform({
  scale: 2,
});

rect.draggable().on("dragmove.snap", (e) => {
const { handler, box } = e.detail;
e.preventDefault();

// Can I get a rbox here?
let { x, y } = box;
if (x < constraints.x) {
  x = constraints.x;
}
if (y < constraints.y) {
  y = constraints.y;
}
if (box.x2 > constraints.x2) {
  x = constraints.x2 - box.w;
}
if (box.y2 > constraints.y2) {
  y = constraints.y2 - box.h;
}

handler.move(x, y);
});
```

**Comment by Fuzzyma** [comment]
The position is correct but only in the coorddinate system of the element itself. It is *really hard** to give a rectangular constraint for a rotated object in untransformed coordinates.

However, to get the `rbox()` in dragmove, just call `rect.rbox(draw)` in your example.

**Comment by moayuisuda** [comment]
The rbox obtained in this way is the current rbox, if there is a way to get a new rbox of the element after the drag just like `box`? So that I can judge whether there is a collision after moving.

**Comment by Fuzzyma** [comment]
Just move the element yourself with the provided move function and check the rbox afterwards. Therre is no way of getting the rbox of an element if the element is not actually there

**Comment by moayuisuda** [comment]
It's true that predict a rbox is hard, thanks for your reply.btw svg.js is the best svg library I have ever used.

**Comment by Fuzzyma** [comment]
If you want to go hardcore you can iteratively multiply all transformation matrices to come up with the correct matrix to transform your bbox to an rbox but I feel like this is overkill ^^

Thank you!

**Comment by moayuisuda** [comment]
In fact I have tried to find a function like `toRbox(bbox, element)` in doc, I will work on it if I got a time.

**Comment by Fuzzyma** [comment]
Good luck with that. I programmed the `getBoundingClientRect` method for `svgdom`. That was enough for the next time ^^
