### ISSUE TITLE
This plugin is incompatible with the latest version svg.js

### ISSUE THREAD

**Issue by suasti** [svgdotjs/svg.draggable.js#131]
I got ReferenceError:
SVG is not defined
node_modules/@svgdotjs/svg.draggable.js/dist/svg.draggable.js

**Comment by Fuzzyma** [comment]
more context please. Did you include the files in teh correct order? Whee do you got your svg.js from?

**Comment by cornwe19** [comment]
I'm also running into this same error trying to use this plugin against `@svgdotjs/svg.js` version 3.1.1 installed through npm. I'm following the ES import instructions from the readme,
```
import { SVG } from '@svgdotjs/svg.js'
import '@svgdotjs/svg.draggable.js'
```

**Comment by Fuzzyma** [comment]
Are you using native esm support or some kind of bundler? What's your ecosystem?

**Comment by cornwe19** [comment]
This is a NextJS React app using webpack 5.

For what it's worth, I did find a workaround. Looks like if I require the plugin inside a `useEffect` during the first render instead of importing it everything works as expected.

```typescript
import {SVG, Element, Container} from "@svgdotjs/svg.js"

const MyComponent = () => {
  useEffect(() => require('@svgdotjs/svg.draggable.js'), [SVG])
  ...
}
```

**Comment by anup-a** [comment]
Putting it in `useEffect` doesn't seem efficient. Any solution for this one ?

**Comment by cornwe19** [comment]
@anup-a FWIW the workaround I suggested would effectively only render once when the component is mounted. Are you concerned about rerenders?

**Comment by anup-a** [comment]
> @anup-a FWIW the workaround I suggested would effectively only render once when the component is mounted. Are you concerned about rerenders?

Yes. also a little bit worried about the bundling and minification. I don't know how webpack/swc handles such imports.

**Comment by Fuzzyma** [comment]
Is this still an issue? I just tested in a vanilla app and its enough to import both libs after each other and it just works:

```ts
import { Svg } from "@svgdotjs/svg.js";
import "@svgdotjs/svg.draggable.js";

const svg = new Svg().addTo("#app").size(600, 400);

svg.rect(100, 100).fill({ color: "red" }).draggable();
```
