### ISSUE TITLE
Drag is broken if text has a tspan with X attribute set

### ISSUE THREAD

**Issue by eugene-rozov** [svgdotjs/svg.draggable.js#133]
Drag is broken if the text element has a tspan with manually set X attribute. Here is a [sample](https://codepen.io/nazica/pen/powjdEB) — try to drag a rectangle and you see it starts to go off with acceleration while tspan element is not moving using X axis.

Behavior is somewhat similar to [this issue](https://github.com/svgdotjs/svg.draggable.js/issues/132).

**Comment by Glandos** [comment]
This is maybe caused by the fact that `move` will set `x` and `y` for each child instead of setting a `transform` on the parent, as mentioned in svgdotjs/svg.js/issues/1110

Draggable should have an option to use translate instead of move. For now, I use:
```js
element.on('dragmove.namespace', e => {
    const { handler, box } = e.detail
    e.preventDefault()
    handler.el.translate(box.x, box.y)
})
```

**Comment by Fuzzyma** [comment]
This issue is fixed in newer versions of svg.js
