### ISSUE TITLE
"SVG is not defined" in Nuxt plugin

### ISSUE THREAD

**Issue by fclef819** [svgdotjs/svg.draggable.js#134]
My nuxt plugin
```
/* @/plugins/svg.ts */
import { SVG } from '@svgdotjs/svg.js'
import '@svgdotjs/svg.draggable.js'
...
```
Error
![image](https://user-images.githubusercontent.com/52777919/136492064-e7e99b04-3768-4194-b78b-d9d2bebb60b5.png)

package.json
```
    "@svgdotjs/svg.draggable.js": "^3.0.2",
    "@svgdotjs/svg.js": "^3.1.1",
```

How can I do?

**Comment by fclef819** [comment]
Okay, I'll proceed with the development with this code.
Thanks a lot!

**Comment by MedvedskiyGordey** [comment]
try doing the following import:
`import '@svgdotjs/svg.draggable.js/src/svg.draggable'`
