### ISSUE TITLE
Dragging SVG element within zoomed/scaled HTML elements

### ISSUE THREAD

**Issue by Glandos** [svgdotjs/svg.draggable.js#135]
I am experiencing issues with dragging SVG element that belong to an SVG document within a DIV element, transformed with a `scale`.

Here is the codepen: https://codepen.io/glandos/pen/LYjMQzK

- The first one is OK, no transform.
- The second one has the transform on SVG, everything is OK.
- The last one has the same transform, but on the HTML element, parent of the SVG document. The SVG then has exactly the same size, but dragging the circle leads to an incorrect position. The position seems to have an offset, based on the scale.

My findings so far lead me to the computation of the bounding box, which seems erroneous. But I can't either find why, and especially **how** to correct this. I have access to the transform, so I am able to build the correct matrix for that scale transformation.

Maybe it has something to do with `transform-origin`, but I have no clue on how to solve this. I don't really know if it's a bug from draggable itself, but it's an edge case that should at least be documented.

**Comment by Glandos** [comment]
I just found that it does not work with Firefox 95, but this is OK with Chromium 93. So… I'll have to explore something else to solve this.

**Comment by Fuzzyma** [comment]
@Glandos FF seems to report the wrong matrix for `getScreenCTM()` in this case. This is a FF bug and should be reported

**Comment by Glandos** [comment]
I'm closing it then, it should be tracked in Firefox issue tracker.

**Comment by Fuzzyma** [comment]
Well we can leave it open until the FF bug is closed since it is a known issue and people might stumble across this

**Comment by landgenoot** [comment]
I thought this was normal behavior until I checked my code in Chrome.

@Glandos this is the workaround that I used. Scale should be fetched from the parent element DOM.

```
.on('dragmove.namespace', e => {
  const { handler, box } = (<any>e).detail;
  e.preventDefault();
  let { x, x2, y, y2 } = box;
  y = dragStartBox.y + (y - dragStartBox.y) / scale;
  y2 = dragStartBox.y2 + (y2 - dragStartBox.y) / scale;
  x = dragStartBox.x + (x - dragStartBox.x) / scale;
  x2 = dragStartBox.x2 + (x2 - dragStartBox.x) / scale;
  handler.move(x, y);
 });
```

**Comment by Glandos** [comment]
Well this seems not to be a universal workaround. I **have** to use `translate` instead of `move` because my SVG has nested transformations (rotate + zoom at different level), and my dragged component act weirdly then.

Moreover, x2 and y2 are never used in this code, is this correct?

**Comment by Fuzzyma** [comment]
This now seems to work correctly in FF and Chrome:
https://codepen.io/fuzzyma/pen/qBGwomg
