### ISSUE TITLE
How to drag multiple SVGjs objects with one handle?

### ISSUE THREAD

**Issue by ps1x** [svgdotjs/svg.draggable.js#136]
Is there easy way to say, create group of elements, add handle and make this group draggable via that handle?
Some pseudo-code to illustrate what i mean:

`const group = new SVG();
const handle = new SVG().rect(10,10).draggable(); //this is handle
const text = new SVG().text('This text should be draggable with handle');
group.add(handle).add(text);
`

i tried 
`
const group = new SVG().draggable();
const handle = new SVG().rect(10,10);
const text = new SVG().text('Some text');
`
but problem here is that text also becomes draggable and coordinates in the on('dragmove') only jitter a little and return back to original when you try to move it.

**Comment by Fuzzyma** [comment]
You can make the handle draggable, bind to the dragmove event and move the group in the callback yourself

```js
const g = canvas.group()
g.text('asdasd')
g.rect(10, 10).draggable().on('dragmove', (ev) => {
  ev.preventDefault() // no default drag

  const {x, y} = ev.detail.box
  g.move(x, y)
})
```

I wrote this from memory. Consolt the readme on errors

**Comment by ArbitRandomUser** [comment]
neat ! was looking for something like this .

also @ps1x in-case didn't know you can have multi line fixed width fonts
using three back-ticks 

```
hello world
ssup
```
