### ISSUE TITLE
Property 'draggable' does not exist on type 'Rect'

### ISSUE THREAD

**Issue by arezookheirabedi** [svgdotjs/svg.draggable.js#138]
hi 
in a vanila-typescript project, i get a type error for adding draggable
svg: SVG.Doc
const a= this.svg.rect(3,3).draggable(true)

**Comment by Fuzzyma** [comment]
Did you use svg.js v2? SVG.Doc doesnt exist in v3 anymore.

This works in newer versions:

```ts
import * as SVG from "@svgdotjs/svg.js";
import "@svgdotjs/svg.draggable.js";

let a: SVG.Svg
a.draggable()
```
