### ISSUE TITLE
Groups aren't dragged, but their content is

### ISSUE THREAD

**Issue by kai-dj** [svgdotjs/svg.draggable.js#139]
When I add `.draggable` to a Group(/G) and drag it, the attributes of the Children of the Group are 
changed, but not the x/y-attributes of the Group itself. 
For my usecase it would be crucial, that the attributes of the Group itself change.

I found a reference to that behaviour in a comment in the `move` function regarding svg-elements "// Thats why we handle them the same as groups" but no further information or code handling G-elements diffent than other elements.

If that behaviour is not a bug and intended I propose that we extend the documentation to describe the behaviour on Group-elements. In that case hints on the location of the deviating move-code would be much appreciated (so I could change it for myself). 

EDIT I see that G-elements don't have x/y attributes - but they still kann be moved themselves via Matrix - when I use a class `MyG extends G` and overwrite the `dmove`-function to use `translate` dragging works as expected. /EDIT

**Comment by Fuzzyma** [comment]
Just use the translate function if you want to translate the group.
The move function makes sure that the bounding box moves (which is not the case for translations). So moving a group will move its contents because a group is just a grouping of elements and doest have geometry by itself

**Comment by kai-dj** [comment]
Still - shouldn't dragging a Group drag the Group and not drag the children? 
Why should draggable use move in this case?
