### ISSUE TITLE
Add TypeScript definition file

### ISSUE THREAD

**Issue by d-asensio** [svgdotjs/svg.draggable.js#59]
I suggest to add a TypeScript definition file like in svg.js project, I found one definition for this project here:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/svgjs.draggable/svgjs.draggable.d.ts

But I think it's wrong because the type of .draggable isn't always an Element, it depends on the method calls chain before it. I'm not used to write TypeScript at all (I just started yesterday) but modifying the aforementioned definition replacing 'Element' by 'this' VisualStudio Code stops to warn me... so I think it's correct.

If someone more used in TypeScript can check this I can commit the file to this repo an modify the file at DefinitelyTyped.

**Comment by Fuzzyma** [comment]
As far as I know `draggable()` always returns an element. However the linked ts is outdated.
Since I am not familiar with that I let this open for other developers ;)

**Comment by d-asensio** [comment]
When I say "the type of `.draggable()` isn't always an Element" I mean that according to the official TypeScript definition file (https://github.com/wout/svg.js/blob/master/svg.js.d.ts), `.draggable()` must return the type of the previous element on the chain, consider the following code:

``` TypeScript
let draw = SVG('drawing');

let group = draw.group();
let rect = draw.rect(15, 15).fill('red').move(20, 20);

let rect_draggable = rect.draggable();
let group_draggable = group.draggable();

group_draggable.add(rect_draggable);
```

Here the type of `group` is `svgs.G` but the type of `rect` is `svgs.Rect` and `.draggable()` mustn't modify the type of these elements.

With the definition file at DefinitelyTyped everything returned by `.draggable()` is an `Element` and this should work with `svgs.Rect` because by hierarchy `svgjs.Rect` extends `svgjs.Shape` and `svgjs.Shape` extends `svgjs.Element`, the problem is with `group_draggable`, in this case the `group_draggable` type is `svgjs.G` and `svgjs.G` extends `svgjs.Container` not `svgjs.Element`.

**Comment by d-asensio** [comment]
Anyway... I don't know if replace `Element` by `this` at definition file is the best option to describe that, so it could be better if we wait for someone more experienced on TypeScript.

Thanks ;)

**Comment by Fuzzyma** [comment]
I see your point - but every thing in svg.js extends from SVG.Element ;).
However `this` is the far better way :)

**Comment by d-asensio** [comment]
Ok, so then there are another mistake in https://github.com/wout/svg.js/blob/master/svg.js.d.ts, as you can see there are not hierarchy relation between `svgjs.Container`and `svgjs.Element`, must `svgjs.Container` extend `svgjs.Element`?

**Comment by Fuzzyma** [comment]
no, `SVG.Container` extends from `SVG.Parent` which itself extends `SVG.Element`.
I think that is correctly stated in the file

**Comment by d-asensio** [comment]
Ok, I just see it, so... VisualStudio says me that:
<img width="550" alt="captura de pantalla 2016-05-26 a las 0 17 42" src="https://cloud.githubusercontent.com/assets/13970905/15558081/a0b5561c-22d7-11e6-82bd-9401d379aa6a.png">

Any idea? 

Thanks. ;)

**Comment by d-asensio** [comment]
Ok, I just see it... but VisualStudio says that:

<img width="513" alt="captura de pantalla 2016-05-26 a las 0 26 01" src="https://cloud.githubusercontent.com/assets/13970905/15558191/8f5f7432-22d8-11e6-8cfa-21ca8c0bf8ec.png">

Any idea? 

Thanks ;)

**Comment by Fuzzyma** [comment]
Lets ask the one who did it ;)
@rdfriedl may you take a look?

**Comment by rdfriedl** [comment]
i dont have the time to test this at the moment, but from what i can tell its the fact that the svg.draggable.d.ts is returning a type `svgjs.Element` instead of what type it was called on.

so in the code above when you create the group.
```javascript
//this returns a type svgjs.G
var group = draw.group();

//where as this makes it a svgjs.Element because the draggable function returns type svgjs.Element
var group = draw.group().draggable();

//and SVG.Element dose not have the method add()
group.add(draw.circle(10).fill('red'))
```

so yes, the `draggable()` should return `this` and not `svgsj.Element`

hope that helps :D

**Comment by jaichandra** [comment]
Can I use this library with Typescript? I tried but I get "draggable is not a function" error. If not, how else can I use this library?

**Comment by maxailloud** [comment]
I have the same issue but only with a production build made out with AngularCLI.
In local it works fine but with a production build I also get `.draggable is not a function`.

Did someone already run on this issue?

**Comment by Fuzzyma** [comment]
This issue is highly outdated. In the meantime there was a major version bump add there also is a typescript file now. Please open a new issue when you run into problems with that!

**Comment by maxailloud** [comment]
Yeah right. This one might be closed no?
