### ISSUE TITLE
SVG Not founf

### ISSUE THREAD

**Issue by farrukhpisces** [svgdotjs/svg.draggable.js#63]
Hi I am using SVG.js for the first time.
The problem is that when I use SVG.js alone every thing works fine. But i need draggable and other functionality too. The problem comes when I used svg.draggable.js, then i gives an error say 
"SVG is not defined"

**Comment by wout** [comment]
Did you load the draggable plugin before or after SVG.js?

**Comment by farrukhpisces** [comment]
its after SVG.js

**Comment by Fuzzyma** [comment]
Show is your code please

**Comment by farrukhpisces** [comment]
ok.
my script bundling is as
```
 bundles.Add(new ScriptBundle("~/bundles/MyScript").Include(
                       "~/Scripts/MyScript/svg.js"));

            bundles.Add(new ScriptBundle("~/bundles/MyScript").Include(
                       "~/Scripts/MyScript/draggable.js"));
```
and my script code is 
`var draw = SVG("myDiagramDiv").size(300, 300)
            alert(draw);
            var rect = draw.rect(100, 100).attr({ fill: 'white', stroke: 'black', margin: 5 });
            rect.draggable();`
