### ISSUE TITLE
NPM version of 2.2.0 appears different to Bower version

### ISSUE THREAD

**Issue by mohantaylor** [svgdotjs/svg.draggable.js#65]
I just recently moved from bower to npm, and the code pulled down for version 2.2.0 is different when pulling from the npm repo than what is in github or bower's repo.  
For example. startPoints doesn't contain the transform property in the npm version.

**Comment by Fuzzyma** [comment]
hm thats odd. However I dont know what to do about it. For a quickfix just use 2.2.1 :). Thanks for reporting!

**Comment by mohantaylor** [comment]
Looks like 2.2.1 isn't on npm yet?

**Comment by Fuzzyma** [comment]
Oh - well - it now is :)

**Comment by mohantaylor** [comment]
Thanks :)
