### ISSUE TITLE
No way to prevent drag start

### ISSUE THREAD

**Issue by ArtyomShegeda** [svgdotjs/svg.draggable.js#66]
Nor **beforedrag** neither **dragstart** events can be cancelled.
If there are some conditions affect drag logic these cannot be reflected in the code.

**Comment by Fuzzyma** [comment]
Do you mean preventDefault when talking about cancelation?

**Comment by supdegrave** [comment]
dragmove allows preventDefault(), but it would be great if it was also supported in beforedrag and dragstart.

**Comment by Fuzzyma** [comment]
I can see a good reason to cancel beforedrag. If you cancel it, drag will not happen. But canceling dragstart does not serve a purpose. At least not at the point where it is fired. Same goes for dragend.

**Comment by Askadar** [comment]
So, any progress on this one? It's kinda strange that we can't prevent dragging. 
Simple example - game with draggable elements, would be strange to enable or disable collection of elements (and there could tens if not hundreds of them) every time some flag changes other than just check if flag allows drag on user interaction with a single element.

**Comment by Fuzzyma** [comment]
I implemented the possibility to prevent `beforedrag`. Try the latest commit in master

**Comment by supdegrave** [comment]
Would it be possible to update the documentation to reflect that beforedrag is now preventable, with an example?

**Comment by Fuzzyma** [comment]
done

**Comment by supdegrave** [comment]
Thanks. Another issue: it seems like bower install / bower update doesn't see this change. Is that because semver didn't update? 
Old: `/*! svg.draggable.js - v2.2.1 - 2016-08-25`
New: `/*! svg.draggable.js - v2.2.1 - 2017-04-18`

**Comment by Fuzzyma** [comment]
I said "try the latest commit in master" and waited for feedback. I didn't want to publish without that being tested by users. So if you can confirm that this works as you would expect, report Bach and I release a new version

**Comment by supdegrave** [comment]
Ah, OK. I'll check it out and let you know.

**Comment by supdegrave** [comment]
I'm hitting an error when I try to use `beforedrag`, because `this.el.event` is undefined. Here's a simplified example: 

```
function drawImage(asset, pos) {
    var img = _svg.image(asset.url, asset.imageWidth, asset.imageHeight)
            .center(pos[0], pos[1])
            .draggable();

    img.on('beforedrag', imageOnBeforeDrag)
}

function imageOnBeforeDrag(svgEvt) {
    if (!_allowDrag) {
        svgEvt.preventDefault();
    }
}
```

This results in the following error: 

```
Uncaught TypeError: this.el.event is not a function
    at DragHandler.start (svg.draggable.js:60)
    at e.<anonymous> (svg.draggable.js:18)
```

**Comment by Fuzzyma** [comment]
@supdegrave which version of svg.js? 2.5.0 is minimum required

**Comment by supdegrave** [comment]
Since this update isn't yet available in bower, what's your suggestion for
best way to get it locally with all appropriate dependencies for testing?
I'd love to help out, but "Try the latest commit" isn't particularly
helpful.

**Comment by supdegrave** [comment]
```
supdegrave:Client stuart$ bower info svg.js 
bower svg.js#*                  cached https://github.com/svgdotjs/svg.js.git#2.6.1
bower svg.js#*                validate 2.6.1 against https://github.com/svgdotjs/svg.js.git#*
```

**Comment by Fuzzyma** [comment]
Google knowledge
```
bower install https://github.com/svgdotjs/svg.draggable.js.git#master
```

**Comment by supdegrave** [comment]
Thanks for the smartass reply. :(

That still doesn't help with dependencies.

**Comment by Fuzzyma** [comment]
Iam pretty sure that you have more bower knowledge than me. I never use it. The upper statement installs the current master of svg.draggable.js and version 2.6.1 of svg.js as dependencie - so everything you want.
So I cant see your problem...

**Comment by supdegrave** [comment]
Following up: I had to abandon my effort to utilize beforedrag, because IE11 has a bug in which it doesn't properly handle `preventDefault` on `CustomEvent` events - it doesn't result in `defaultPrevented` returning `true`. 

If I have free time at some point, I'll look deeper into this and see if I can submit a pull request fixing this issue for IE. There seem to be a few strategies available online to do so.

**Comment by Fuzzyma** [comment]
Mh that's to bad. When you find something it might be useful to have it in the svg.js core. Feel free to raise an issue there. 
Does this happen in every version of IE ( or edge)?

**Comment by supdegrave** [comment]
IE11 only, as far as I'm aware. Yeah, if I figure out how to deal with this
I'll do so in svg.js core so it's available everywhere.

**Comment by Fuzzyma** [comment]
Cool. Thanks!

**Comment by newsekaes** [comment]
I also encountered the above problem in IE11. If you use `preventDefault` on `CustomEvent`, the `defaultPrevented` is still `false`. IE11 is too disappointing

**Comment by Fuzzyma** [comment]
This should no longer happen with svg.js v3 when you use the shipped polyfills.
