### ISSUE TITLE
Issue adding to different groups

### ISSUE THREAD

**Issue by oscarcalvo** [svgdotjs/svg.draggable.js#68]
Hi:

I have a svg with several shapes. When user selects one or several of them I creaste a group, make it draggable with your plugin, and add them to group. So user can dragg all selected elements together and it works well. At the end event I remove draggable from the group.
Problem is when user selects again one element previously dragged. When I add the same element to a new group (because user can select different elements), this element is reset to initial position instead of current position. Also I cant use same group and remove rest of elements because they have same behaviour, are reset to previous position.
Any idea how I can do it?

Thanks a lot.

**Comment by Fuzzyma** [comment]
You can try the `ungroup()` or `flatten()` feature which was introduced some while ago. Call it on the group like `myGroup.ungroup()` and all elements from the group are moved out of the group and remain the same visual representation. You also can try `toParent()` which is used from `ungroup()` internally. It lets you move a child to another parent without changing the visual representation.

**Comment by oscarcalvo** [comment]
Simple and easy, I didnt know this way.

Thanks Fuzzyma

**Comment by wout** [comment]
Here is some more info on `ungroup()`:

https://svgdotjs.github.io/manipulating/document-tree/#ungroup-flatten
