### ISSUE TITLE
dragstart and dragmove both fire on click

### ISSUE THREAD

**Issue by supdegrave** [svgdotjs/svg.draggable.js#69]
It appears that simply clicking on draggable items fires any dragstart or dragmove handlers. This seems like an odd implementation.

**Comment by Fuzzyma** [comment]
Feel free to make suggestions. Its for simplicity that dragstart fires when you press mousedown. dragmove is fired on every update which also occurs when clicking

**Comment by KorokTheWhite** [comment]
@supdegrave Hope [this](https://stackoverflow.com/questions/46798428/drag-event-is-being-fired-on-click) is what you looked for and hope this helps other people

**Comment by amitguptagwl** [comment]
This is how I've solved this problem;

```js
function onMouse(shape, dragCB, clickCB){
    var mousestate = 0;
    shape.on( 'mousedown', function() {
        mousestate = 1;
    });
    shape.on( 'mousemove', function() {
        if(mousestate === 1) mousestate = 2;
    });
    shape.on( 'dragend', function(e) {
        if(mousestate === 2) {
            dragCB(e);
        }else{
            clickCB(e) 
        }
        mousestate = 0;
    });
}
```

**Comment by Fuzzyma** [comment]
In the current version, the drag event is only bound after the first click happened. So that issue should be resolved
