### ISSUE TITLE
select & resize not working anymore when draggable - on touch devices

### ISSUE THREAD

**Issue by razvanioan** [svgdotjs/svg.draggable.js#76]
On touch based devices (At least iOS 10 & 11), if you attach draggable to the element and it also has select / resize (on mouse click on that element) than the select / resize points are never rendered anymore.

I suspect due to a preventDefault or stopPropagation, but it's strange as on PC it works

**Comment by razvanioan** [comment]
1. This breaks `select / resize` on touch devices

```javascript
rect
  .draggable()
  .on('click', function(){
    this
      .selectize()
      .resize()
  })
```

2. This is working on touch devices too

```javascript
rect
  .on('click', function(){
    this
      .draggable()
      .selectize()
      .resize()
  })
```

It's working because I catch the click event to activate `select / resize` too

**But**

* It's nice that with first version you can directly move the element (including on mobile devices)
* doing so, I need to cancel draggable too whenever I cancel select / resize (on window click elsewhere but that element)

At least I have a workaround for the moment !

**Comment by Fuzzyma** [comment]
You need to seperate a click from a drag. With the current master you can do that easily. Take a look here: https://github.com/svgdotjs/svg.draggable.js/issues/111#issuecomment-590315242
