### ISSUE TITLE
Firefox calculates weird SvgMatrix values on transition out of fullscreen

### ISSUE THREAD

**Issue by supdegrave** [svgdotjs/svg.draggable.js#78]
I have an application which goes into fullscreen to present SVG-based interactive lessons, which involve dragging image sprites into target locations. I determine if the drop point is inside the target location, using the following code (simplified for demo purposes): 

```
function imageOnDragEnd(svgEvt) {
        var svgPoint = svgEvt.detail.p,
            dropZoneId = _.find(_destinationIds, function(destinationId) {
                var svgElement = SVG.get(destinationId);
                return svgElement && svgElement.inside(svgPoint.x, svgPoint.y);
            });

        // do something with dropZoneId
    }
}
```

Because user actions in the browser can result in dropping out of fullscreen, it's good for the lessons to continue to function in the event of an unexpected fullscreen exit. On MacOS, this works as expected in Chrome and Safari, but in Firefox the calculation which happens in `DragHandler.prototype.transformPoint` results in negative x/y values on the return value. 

I modified `DragHandler.prototype.transformPoint` to log (on mouseup) the incoming SvgPoint, the current SvgMatrix, and the outgoing SvgPoint, as follows: 

```
DragHandler.prototype.transformPoint = function(event, offset){
    event = event || window.event
    var touches = event.changedTouches && event.changedTouches[0] || event
    this.p.x = touches.pageX - (offset || 0)
    this.p.y = touches.pageY
    var matrixTransform = this.p.matrixTransform(this.m);

    if (event.type === 'mouseup') {
        console.log('========================');
        console.log(navigator.userAgent);
        console.log('========================');
        console.log(this.p);
        console.log(this.m);
        console.log(matrixTransform);
        console.log('========================');
    }

    return matrixTransform
}
```

Here are the results, cleaned up to be more readable, and to remove logging differences between browsers. In each case, the first set of values is in fullscreen, and the second set after exiting fullscreen by the ESC key.  

```
========================
Chrome
========================
SVGPoint {x: 438, y: 192}
SVGMatrix {a: 1, b: 0, c: 0, d: 1, e: -128, f: -0}
SVGPoint {x: 310, y: 192}
========================
SVGPoint {x: 576, y: 141}
SVGMatrix {a: 1, b: 0, c: 0, d: 1, e: -252, f: 44}
SVGPoint {x: 324, y: 185}
========================

========================
Safari
========================
SVGPoint {x: 377, y: 204}
SVGMatrix {a: 1, b: 0, c: 0, d: 1, e: -128, f: -0}
SVGPoint {x: 249, y: 204}
========================
SVGPoint {x: 511, y: 187}
SVGMatrix {a: 1, b: 0, c: 0, d: 1, e: -252, f: 14.5}
SVGPoint {x: 259, y: 201.5}
========================

========================
Firefox
========================
SVGPoint { x: 388, y: 192 }
SVGMatrix { a: 1, b: -0, c: -0, d: 1, e: -128, f: 0 }
SVGPoint { x: 260, y: 192 }
========================
SVGPoint { x: 520, y: 142 }
SVGMatrix { a: 1, b: -0, c: -0, d: 1, e: -715, f: -340.5 }
SVGPoint { x: -195, y: -198.5 }
========================
```

Note above that Firefox returns an SVGPoint with negative x/y values, and below the dramatic difference in the fullscreen/normal SVGMatrix values: 

```
========================
Chrome
========================
SVGMatrix {a: 1, b: 0, c: 0, d: 1, e: -128, f: -0}
========================
SVGMatrix {a: 1, b: 0, c: 0, d: 1, e: -252, f: 44}
========================

========================
Safari
========================
SVGMatrix {a: 1, b: 0, c: 0, d: 1, e: -128, f: -0}
========================
SVGMatrix {a: 1, b: 0, c: 0, d: 1, e: -252, f: 14.5}
========================

========================
Firefox
========================
SVGMatrix { a: 1, b: -0, c: -0, d: 1, e: -128, f: 0 }
========================
SVGMatrix { a: 1, b: -0, c: -0, d: 1, e: -715, f: -340.5 }
========================
```

I suspect this is an issue with Firefox's implementation of `getScreenCTM`, but perhaps there's something that can be done to mitigate this issue in svg.draggable.js as well? I'm planning to report the issue to Mozilla also.

**Comment by Fuzzyma** [comment]
Actually svg.js uses a way to negate Browserdifferences in getScreenCTM. I figure you used the svg.js method `screenCTM()` and not the native one, right? Thats a bit weired. You can look into the code of svg.js and find the screenCTM method. You will clearly see where the workaround happens. Maybe logging, debugging, fiddling there will help? But I also have no real answer to that problem :/

**Comment by supdegrave** [comment]
I'm not calling `screenCTM()` directly. You can see how I access the point data in my `imageOnDragEnd` function, at the top. 

When a drop happens, `DragHandler.prototype.end` is called, which steps through `DragHandler.prototype.transformPoint` before firing `dragend`, which then calls my `imageOnDragEnd`, where I use `svgEvt.detail.p.x` and `svgEvt.detail.p.y`.

**Comment by supdegrave** [comment]
FYI, also reported to Mozilla: 

https://bugzilla.mozilla.org/show_bug.cgi?id=1445191

**Comment by supdegrave** [comment]
If you have a customized `screenCTM` method that handles browser differences, why do you use native `getScreenCTM` in `DragHandler.prototype.start`?

**Comment by Fuzzyma** [comment]
Guess you just found the error in the code ^^.
I am pretty sure this bit was written when the method wasn't around in the core lib.

I really thought I checked if the native version is used the last time I looked into this issue. Seems like I am blind... Feel free to open a pr to correct that one!

**Comment by supdegrave** [comment]
I'm not sure what to change. I tried changing svg.draggable.js:74 from: 

`this.m = this.el.node.getScreenCTM().inverse()`

to: 

`this.m = this.el.screenCTM().inverse()`

but that broke my code in other ways. 

Making this work in Firefox isn't critical, but would be nice. If you can give me a clearer pointer I'll see if I can figure it out - or perhaps you now have enough information?

**Comment by Fuzzyma** [comment]
I think the line `return this.p.matrixTransform(this.m)` needs to be changed into `return this.p.matrixTransform(this.m.native())` to make it work.
