### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by pjfsilva** [svgdotjs/svg.draggable.js#81]
It seems that a v2.2.2 is long overdue or it's just my luck because immediately after upgrading to v.2.2.1 I encountered #67 which seems like a big bug that warrants a new release.

Is there anything needed to test/fix before a new release is done? I would love to help where I can if anything is missing.

(sorry for being a bit annoying, bothering with this while I can just use master and that's it but for tracking purpose it's always better to use fixed versions)

**Comment by Fuzzyma** [comment]
Does it work with master for you? Because I cannot see any commits fixing 67.

**Comment by pjfsilva** [comment]
yes, master works. If I would guess it's because 5143ce9ed1d2546890b6a6d5775163d43f85fe64
