### ISSUE TITLE
draggable prevents ondblclick event on objects

### ISSUE THREAD

**Issue by haimmamou** [svgdotjs/svg.draggable.js#83]
Given an object created
When draggable() enabled
Then it can be dragged but ondblclick event will not be thrown/caught anymore
I work on surface pro 4 / google chrome.
I need a way to display edit form on double click an object in fact.

so this works:
var test = draw.rect(100,100).center(150, 150).on('dblclick', function(){alert('Ok !');});
while this doesn't:
var test = draw.rect(100,100).center(150, 150).draggable().on('dblclick', function(){alert('BIM !');});

**Comment by 13djwright** [comment]
I cannot replicate this using the latest package via npm. Dragging and double click seems to work.
