### ISSUE TITLE
Wrong positioning of sub-elements with 'nested' after dragging the nested

### ISSUE THREAD

**Issue by amitguptagwl** [svgdotjs/svg.draggable.js#86]
I'm facing a weird issue in positioning of sub-elements with draggable 'nested'.  

**Goal**: Create a shape (rect, circle, poly) > create points(small circle) inside the shape. So when I move the shape all the points inside the shape should also move.

**Implementation without nested**: To determine the position for circle point to draw, I'm subtracting SVG box offset from actual cursor position. And it works fine.

```js
mySVGCanvas.circle().radius(3).attr({ cx: e.x - canvasOffset.x , cy: e.y - canvasOffset.y });
```
**Implementation with nested**: I'm using the same logic here

```js
rect.parent().circle().radius(3).attr({ cx: e.x - canvasOffset.x , cy: e.y - canvasOffset.y });
```

Now I draw the rect and then draw points on that. Everything seems fine. But actually these are relative to the initial position of nested. 

I move the nested to x+n position >  I draw another point > but this time it is drawn on `cursor.x + n position`.

**Comment by Fuzzyma** [comment]
I read this 3 times but still cannot follow your steps. Please create a jsfiddle which shows what you want

**Comment by amitguptagwl** [comment]
Sorry for the confusing language; Here is the link

https://jsfiddle.net/s06mfv5u/1/

* Use shift key to draw the point

In the above example, the issue I'm facing is working fine but points are not moving along with the nested. On my original application, points are moving but being drawn on the wrong position. Please check the above link.

**Comment by amitguptagwl** [comment]
I've found the solution. When we drag nested, it's new position is relative to it's initial position. I beileve because of `transform` function. So this function works

`cx: e.x - canvasOffset.x - nested.x`
