### ISSUE TITLE
Moving at high magnification

### ISSUE THREAD

**Issue by Andreslav** [svgdotjs/svg.draggable.js#87]
Hello!
I have a small problem: if you increase the object and then move it - it behaves unpredictably! I'm not special, and so I decided to write here.

The code itself: https://codepen.io/Andreslav/pen/qKjKaK
Function of moving on line 130 (draggable (group)).
After it, and the function resize.

What do you advise?

**Comment by Fuzzyma** [comment]
I advice you to ask this question on stackoverflow where we have a dedicated tag for svg.js
