### ISSUE TITLE
Constraint options don't work properly on rotated group items

### ISSUE THREAD

**Issue by pjfsilva** [svgdotjs/svg.draggable.js#88]
https://codepen.io/sapot/pen/gKzwPE

You can see the pink rectangle constraints work Ok but the green one, since it's rotated doesn't work very well. It seems it is constrained into his own coordinate space which is technically understandable but from an usage point of view I expect it to conform to the 'whole' canvas as this is usually done to constrain drag to a specific space. 

Any way I can work around this or to easily fix this?

**Comment by pjfsilva** [comment]
I see what you mean and will investigate this. 

As a 'crude' approach can't we convert the mouse event point  to an SVG point based on the SVG root coordinate system and use that to compare with the constraints?

I understand it will not be pixel perfect but a much better solution than the current that is plain broken for rotated elements and seems kind of easy to do.

**Comment by Fuzzyma** [comment]
when you do that, you would end up with a mouse constraint and not a shape constraint. so when you click at the very outer edge of the shape and drag it you can almost completely move it out of the constraints. I dont think that is useful at all

**Comment by 13djwright** [comment]
You can sort of work around this. I am sure there is a way to make it even better for calculating a separate grouping rather than by hand as well.

https://codepen.io/13djwright/pen/vrVwrV

**Comment by pjfsilva** [comment]
It seems that is better but still isn't generic, it's totally dependent on adjusting the coordinates on the constraints, just make the rectangle be 50,100 and it's screwed, try 50,300 and it's unusable. Actually in my real use case I already apply draggable to a parent group but rotation is only done on a child group :) 

now that's ok if you can find a formula to convert the constraints automagically and we do it on the plugin. probably we can do it by using the rbox initially and adapt the constraints?

**Comment by Fuzzyma** [comment]
hehe - very nice :)

**Comment by TheBritGit** [comment]
@pjfsilva did you find any solution to this issue?

I'm trying to unsuccessfully constrain a rotated rect. I get the same as your codepen example where it appears as if the constrain is rotated with the shape, not the canvas. I figured it probably had something to do with the plugin using bbox() instead of rbox() but I'm new to svg so a bit lost on how to rectify!

**Comment by TheBritGit** [comment]
@Fuzzyma I have been trying without luck, hence seeing if @pjfsilva had come up with anything. I'm fairly new to svg so trying to learn so will see if I can come with anything. It's okay using rbox but it still has the transformed matrix that messes it up, so trying to get my head around it all
