### ISSUE TITLE
Force 'drag start' from a method?

### ISSUE THREAD

**Issue by pjfsilva** [svgdotjs/svg.draggable.js#89]
OK, this is gonna sound a bit weird but I have a use case where I'm creating a new draggable element and I want the user to click the 'new' button -> elements gets created, .draggable is called and then the element is immediately put into 'drag mode' (i mean you move the mouse and the element comes with it).

In terms of the plugin what I need is to allow for the 'drag' operation to start from a method call and not the mousedown on the element.

1) Is there any way to achieve this with the current plugin version? 

I couldn't find a way so I at the end of the plugin, inside SVG.extend I just added a new method:

````
    draggableStart : function(e) {
      var dragHandler = this.remember('_draggable') || new DragHandler(this)
      dragHandler.start(e);
    }
````

2) Is this something that looks useful to be included in the plugin, probably in a 'nicer' way? (if we want to avoid exposing a new method on all elements we could support .draggable('start') for example)

**Comment by Fuzzyma** [comment]
The issue is, that you need a mouseevent to start a drag. As you can see your function also takes a mouse event and passes it in to the start. And when you have the event anyway, you can just relay it to the draggable shape, cant you?

I prefer the solution of just triggering the mousevent on the shape which autmatically starts the dragging:

```js
  el.draggable().fire(mouseEvent)
```

Is that a possible solution to your problem?

**Comment by pjfsilva** [comment]
hmmm... indeed that's possible to do. I tried it before but I forgot my original event is a click so I ended up doing something like this:

`el.fire(new MouseEvent('mousedown', e.originalEvent));`

(e is a jquery event that's why e.originalEvent is used).

This works, is clean and safe. case closed :+1:

**Comment by pjfsilva** [comment]
ok, I detected a problem on IE11 by using my solution. Since my initial event is a click mouse event I can't pass it directly to el so I need to create a new event. 

On IE11 MouseEvent is not supported so some kind of polyfill is needed.
