### ISSUE TITLE
node js import

### ISSUE THREAD

**Issue by borodadada** [svgdotjs/svg.draggable.js#95]
hello, how i can add this plugin in node js?
I use svg.js

`
import * as SVG from 'svg.js';
....
`

svg.draggable.js  ?

**Comment by Fuzzyma** [comment]
just include it as normal and import it. It attaches to the global SVG by default. Make sure that SVG is global though!

**Comment by nameszian** [comment]
```js
import SVG from 'svg.js';
import draggable from 'svg.draggable.js';
```
And then:
```js
const rect = this.draw.rect(100, 100).attr({ fill: '#F06' });
rect.draggable();
```
