### ISSUE TITLE
Droppable support? drag & drop

### ISSUE THREAD

**Issue by pjfsilva** [svgdotjs/svg.draggable.js#97]
Just wondering or doing a feature request if anyone tried to expand draggable so that it works a bit more like 'drag & drop' a bit like jquery Droppable.

So for example imagine I have a bunch of 'products' I want to drag them to a shopping basket. I want when you are dragging the product and are hover the basket, the basket should change colors / CSS. If you drop the product anywhere outside the basket it just returns to initial position.

Something like this: https://jqueryui.com/droppable/#revert

Any tips on how to achieve this?  I'm thinking I need to do a bbox comparison when dragging but I'm a bit afraid on how to do that with a good performance.

**Comment by Fuzzyma** [comment]
Nope -I cannot think of a project doing that.
However I think it is not hard to build that on top of svg.draggable.js.
You can try `mouseover` for your dropzone and check if something is currently dragged. If so, color your dropzone. For the dropevent you can just utilize the `dragend` event and check if the mouse was over the dropzone. If not, use animate, to move the item back where it was
